Flashloan detection bot
LimeChain/forta-starter-kits pull request #10
Opened 2022-05-10 09:09 UTC by dikel

2022-05-10 11:34 UTC, Tdrachev requested changes
Code looks good, only two things I noticed are the things that I specified in the review

2022-05-10 11:34 UTC, Tdrachev commented on flashloan-detector/README.md
> +The agent behaviour can be verified with the following transactions:
Change agent to bot

2022-05-10 11:34 UTC, Tdrachev commented on flashloan-detector/src/agent.js
> +    helper.clear();
Unt tests fails here "helper.clear() is not a function"

2022-05-10 11:55 UTC, notyouraveragedev commented
Also might be a good idea explaining some of the logic behind the profit calculation with comments

2022-05-11 11:54 UTC, Tdrachev approved these changes

2022-05-11 11:54 UTC, Tdrachev commented
LGTM!

2022-05-19 17:49 UTC, christian-forta requested changes
primarily I would ask to double check whether the 5 flash loan providers you identified are consistent across all the chains this bot will monitor.

2022-05-19 17:49 UTC, christian-forta commented on flashloan-detector/src/flashloan-detector.js
> +const { getDydxFlashloan } = require('./detectors/dydx-detector');
are those the common ones for other chains as well?

2022-05-20 11:07 UTC, dikel commented on flashloan-detector/src/flashloan-detector.js
> +const { getDydxFlashloan } = require('./detectors/dydx-detector');
The flashloan providers emit the same events on all chains. Also the detections are not based on a particular address so they should work with all of these protocols on all chains and all of their forks

2022-05-20 16:48 UTC, christian-forta commented on flashloan-detector/src/flashloan-detector.js
> +const { getDydxFlashloan } = require('./detectors/dydx-detector');
Thanks for confirming. Lets get it shipped :)
Pls send me the bot id once you do. We can keep an eye on it over the weekend and then add it to the kit early next week.

2022-05-20 16:48 UTC, christian-forta commented
Woooo! Super excited about this bot!

2022-05-25 08:12 UTC, stoqnkpL approved these changes
Looks great! It will be very interesting to monitor this bot for alerts!

2022-05-25 08:12 UTC, merged