Large balance decrease
LimeChain/forta-starter-kits pull request #14
Opened 2022-05-27 12:49 UTC by dikel

2022-05-31 08:23 UTC, Tdrachev requested changes

2022-05-31 08:23 UTC, notyouraveragedev commented on large-balance-decrease/Dockerfile
> +FROM node:12-alpine
Node image is depricated, as per discussion with haseeb it would be better to upgrade to either 14 or 16

2022-05-31 08:23 UTC, notyouraveragedev commented on large-balance-decrease/package.json
> +  ],
Would be nice to add repository here

2022-05-31 08:23 UTC, notyouraveragedev commented on large-balance-decrease/src/agent.js
> +
Wouldn't it be better to move this to the unit tests?

2022-05-31 13:42 UTC, Tdrachev approved these changes
LGTM

2022-06-01 18:14 UTC, christian-forta requested changes

2022-06-01 18:14 UTC, christian-forta commented on large-balance-decrease/README.md
> +The bot behaviour can be verified with the provided unit tests
do you have a block range/tx pointing to a real world attack we can capture here?

2022-06-01 18:14 UTC, christian-forta commented on large-balance-decrease/bot-config.json.example
> +  "address": "0xe89a6d0509faf730bd707bf868d9a2a744a363c7"
what is this?

2022-06-01 18:14 UTC, christian-forta commented on large-balance-decrease/src/agent.js
> +const ERC20_TRANSFER_EVENT = 'event Transfer(address indexed from, address indexed to, uint256 value)';
how do you think about native assets?

2022-06-07 10:24 UTC, dikel commented on large-balance-decrease/bot-config.json.example
> +  "address": "0xe89a6d0509faf730bd707bf868d9a2a744a363c7"
This is the configuration address. In this case it is the crUNI market from CREAM protocol

2022-06-09 14:12 UTC, merged