Large mint borrow anomaly detection
LimeChain/forta-starter-kits pull request #7
Opened 2022-05-05 10:49 UTC by Tdrachev

Finished bot and it keeps track of mint/borrow amount per account

2022-05-26 14:25 UTC, dikel requested changes

2022-05-26 14:25 UTC, dikel commented on large-mint-borrow-anomaly-detection/src/agent.js
> +  for (let bucket of trackerBuckets) {
Why do we need to push the addresses first and then find the index? Can't we iterate with index and if the address is equal to trackerBuckets[i] => return the index?

2022-05-26 14:25 UTC, dikel commented on large-mint-borrow-anomaly-detection/src/agent.js
> +const ARIMA_CONFIG = {
Have you tested the model with real data? Are these the best params?

2022-05-26 14:25 UTC, dikel commented on large-mint-borrow-anomaly-detection/src/agent.js
> +let aggregationTimePeriod = 1; //The period that is calculated by bucketBlockSize * blockTime
This should be in a bot-config file

2022-05-26 14:25 UTC, dikel commented on large-mint-borrow-anomaly-detection/src/agent.js
> +              BASELINE_VOLUME: Math.floor(low),
Shouldn't the baseline be the predicted value?

2022-05-26 14:25 UTC, dikel commented on large-mint-borrow-anomaly-detection/src/agent.js
> +              BASELINE_VOLUME: low,
Shouldn't the baseline be the predicted value?

2022-05-27 07:42 UTC, dikel approved these changes
LGTM

2022-06-01 18:11 UTC, christian-forta approved these changes

2022-06-01 18:11 UTC, christian-forta commented on large-mint-borrow-anomaly-detection/README.md
> +The bot behaviour can be verified with supplied unit tests
do we have a tx or block range for a real world attack we can reference here?

2022-06-03 06:29 UTC, merged